### ISSUE TITLE
Странная подписка

### ISSUE THREAD

**Issue by Anna-Prokhorova** [daniilkiselev97/meetups-project#10]
catchError не спасет?
Просто немного странно выглядит эта подписка
https://github.com/daniilkiselev97/meetups-project/blob/31391bf24298b157dae8945e860608636dfb07c5/src/app/components/card-user/card-user.component.ts#L118-L125

**Comment by daniilkiselev97** [comment]
https://github.com/daniilkiselev97/meetups-project/commit/8f0261f82958272763ae27a6589dff5c6e2bf198
