### ISSUE TITLE
Типы инпутов логически не совпадают с контролами

### ISSUE THREAD

**Issue by Anna-Prokhorova** [daniilkiselev97/meetups-project#11]
Тут вот тип text, но контрол для email:
https://github.com/daniilkiselev97/meetups-project/blob/31391bf24298b157dae8945e860608636dfb07c5/src/app/components/card-user/card-user.component.html#L7

А здесь наоборот что угодно, но не email. а тип все равно email:
https://github.com/daniilkiselev97/meetups-project/blob/31391bf24298b157dae8945e860608636dfb07c5/src/app/components/card-user/card-user.component.html#L17
https://github.com/daniilkiselev97/meetups-project/blob/31391bf24298b157dae8945e860608636dfb07c5/src/app/components/card-user/card-user.component.html#L24

**Comment by daniilkiselev97** [comment]
https://github.com/daniilkiselev97/meetups-project/commit/92a5424d10992cf34c3a86c10e8cbe33ebff7f80
