### ISSUE TITLE
Можно улучшить процесс создания контролов для формы roles

### ISSUE THREAD

**Issue by Anna-Prokhorova** [daniilkiselev97/meetups-project#12]
Это уже очень круто, но будет еще круче сделать roles формРекордом и в цикле добавлять туда контролы
Текущий подход тоже хорошо, но единственный его минус в создании вспомогательного объекта rolesGroup, а потом еще и через формБилдер создание нового объекта формГруппы из rolesGroup
Если сделаем roles формРекордом, то избежим создания этих дополнительных объектов, а значит на сотые миллисекунд выиграем по времени и немного памяти (на данных более 2000 иногда это критически важно)
https://github.com/daniilkiselev97/meetups-project/blob/31391bf24298b157dae8945e860608636dfb07c5/src/app/components/popup-create-user/popup-create-user.component.ts#L101-L110

**Comment by daniilkiselev97** [comment]
https://github.com/daniilkiselev97/meetups-project/commit/754e48900e13ce7b14fc996c8069f40fc9870177

**Comment by daniilkiselev97** [comment]
через формРекорд не получилось поставить контролы, так как не удалось обойти проверку КонтролНэймов на null никак

**Comment by daniilkiselev97** [comment]
https://github.com/daniilkiselev97/meetups-project/commit/05adc2092be44a6ae389ef353ea688f579807503

**Comment by daniilkiselev97** [comment]
Исправил на FormRecord контролы
