### ISSUE TITLE
В инпутах стоит переделать на контролы

### ISSUE THREAD

**Issue by Anna-Prokhorova** [daniilkiselev97/meetups-project#13]
Если переделать на контролы можно будет обойтись без плохо-читаемого event.target и добавить rxjs оперторов (debounce, distincUntilChanged и тд) чтоб ф-ция не триггерилась на каждый чих пользователя
https://github.com/daniilkiselev97/meetups-project/blob/31391bf24298b157dae8945e860608636dfb07c5/src/app/pages/all-meetups/all-meetups.component.html#L8
https://github.com/daniilkiselev97/meetups-project/blob/31391bf24298b157dae8945e860608636dfb07c5/src/app/pages/all-meetups/all-meetups.component.html#L12

**Comment by daniilkiselev97** [comment]
https://github.com/daniilkiselev97/meetups-project/commit/bed2337d26a077577eb1782bd66eb2540eb00edf
