### ISSUE TITLE
Можно ознакомиться с оптимальным паттерном регистрирования призмовских иконок

### ISSUE THREAD

**Issue by Anna-Prokhorova** [daniilkiselev97/meetups-project#14]
У Призмы есть проблема, что надо постоянно регистрировать иконки для каждого компонента отдельно, хотя многие из них на самом деле переиспользуются среди компонентов.
В нашей команде выработался паттерн для того чтобы эту проблему контрить.
Если вкратце, то регистратор иконок выносится в отдельный модуль, который будет располагаться в shared папке, а дальше там где надо импортим этот модуль.
Посмотреть пример такого модуля можно тут (пункт про регистрацию иконок): https://kb-liga.phoenixit.ru/pages/viewpage.action?pageId=279427968#id-ВнедрениеNx-Частовстречающиесякейсыипредложенияпоихреализации

https://github.com/daniilkiselev97/meetups-project/blob/31391bf24298b157dae8945e860608636dfb07c5/src/app/components/card-user/card-user.component.ts#L60-L65
https://github.com/daniilkiselev97/meetups-project/blob/31391bf24298b157dae8945e860608636dfb07c5/src/app/components/card-meetup/card-meetup.component.ts#L74-L77

**Comment by daniilkiselev97** [comment]
https://github.com/daniilkiselev97/meetups-project/commit/d5f8019f3a1fb75a61e0abeeaad4a567c0c0ae3b#diff-19ccfc75312751ce661fcee2177ca9137a8a09564725976fc782a360ecf32e76

**Comment by daniilkiselev97** [comment]
https://github.com/daniilkiselev97/meetups-project/commit/d5f8019f3a1fb75a61e0abeeaad4a567c0c0ae3b
