### ISSUE TITLE
Большой объект конфига приложения

### ISSUE THREAD

**Issue by Anna-Prokhorova** [daniilkiselev97/meetups-project#2]
Объект с конфигом который ты передаешь вторым параметром в bootstrapApplication есть паттерн выносить в отдельный .ts файл и присваивать в константу которую потом импортишь в main.ts

https://github.com/daniilkiselev97/meetups-project/blob/31391bf24298b157dae8945e860608636dfb07c5/src/main.ts#L25-L43

**Comment by daniilkiselev97** [comment]
https://github.com/daniilkiselev97/meetups-project/commit/88d98abdc5f5e6a50cf5e226db158eafd2449e08
