### ISSUE TITLE
Подписка>функция?

### ISSUE THREAD

**Issue by RizvanDzh** [daniilkiselev97/meetups-project#3]
https://github.com/daniilkiselev97/meetups-project/blob/31391bf24298b157dae8945e860608636dfb07c5/src/app/components/card-meetup/card-meetup.component.ts#L145-L148

Точно ли нужна подписка вместо вызова обычной функции? Можно объяснить

**Comment by daniilkiselev97** [comment]
https://github.com/daniilkiselev97/meetups-project/commit/a8d97f9830346771ba6c14dbf87ea5a14500d797
