### ISSUE TITLE
Типы экшенов можно выносить в enam

### ISSUE THREAD

**Issue by Anna-Prokhorova** [daniilkiselev97/meetups-project#4]
Просто совет выносить типы экшенов в инам, который указывается вверху.
При жесткой типизации файл с экшенами превращается в жесткий boilerplate и полезно иметь сверху такой инам как некое содержание или список экшенов и их типов

https://github.com/daniilkiselev97/meetups-project/blob/31391bf24298b157dae8945e860608636dfb07c5/src/app/store/actions/auth.actions.ts#L5-L17

Пример boilerplate:
![image](https://github.com/daniilkiselev97/meetups-project/assets/59168625/ebb25643-cb05-43ea-9516-061432b265ac)

**Comment by daniilkiselev97** [comment]
https://github.com/daniilkiselev97/meetups-project/commit/d951038b118ebe88c1992c2f4db0aef36cb785ca
