### ISSUE TITLE
TakeUntilDestroyed в конце!

### ISSUE THREAD

**Issue by RizvanDzh** [daniilkiselev97/meetups-project#5]
https://github.com/daniilkiselev97/meetups-project/blob/31391bf24298b157dae8945e860608636dfb07c5/src/app/components/card-meetup/card-meetup.component.ts#L87-L90

TakeUntilDestroyed лучше размещать в конце pipe
Потому что завершенный обсервабл может быть переключен на другой, который не завершится

**Comment by daniilkiselev97** [comment]
https://github.com/daniilkiselev97/meetups-project/commit/9ed679e2befdfdd46533623eaa21491e3addba4f
