### ISSUE TITLE
Избыточное клонирование стейта при его полном обновлении!

### ISSUE THREAD

**Issue by RizvanDzh** [daniilkiselev97/meetups-project#6]
https://github.com/daniilkiselev97/meetups-project/blob/31391bf24298b157dae8945e860608636dfb07c5/src/app/store/reducers/auth.reducer.ts#L9-L24

зачем клонировать все поля предыдущего стейта если возвращаешь полностью обновленный стейт?

**Comment by daniilkiselev97** [comment]
https://github.com/daniilkiselev97/meetups-project/commit/2e57acb22438a29ac1eea4b768298786ee966303
