### ISSUE TITLE
Наверно ненужный инжектор

### ISSUE THREAD

**Issue by Anna-Prokhorova** [daniilkiselev97/meetups-project#7]
Не очень поняла зачем каждый раз когда создаешь ПолиморфКомпонент передаешь инжектор родителя
https://github.com/daniilkiselev97/meetups-project/blob/31391bf24298b157dae8945e860608636dfb07c5/src/app/pages/users/users.component.ts#L33

Prizm это делает под капотом, исключением являются lazy-loaded модули:
![image](https://github.com/daniilkiselev97/meetups-project/assets/59168625/8ec20259-3f51-4f24-a97b-d4387e4a03f3)

И затем в PolymorphOutletDirective:
![image](https://github.com/daniilkiselev97/meetups-project/assets/59168625/6bcbf508-7edd-49a9-8cb6-d76b3f6fd2d6)

**Comment by daniilkiselev97** [comment]
https://github.com/daniilkiselev97/meetups-project/commit/73a0fc6a0560bb5e9bb9968b7eb5dd923028c63f
