### ISSUE TITLE
Маленький стейт в отдельном файле

### ISSUE THREAD

**Issue by Anna-Prokhorova** [daniilkiselev97/meetups-project#8]
Я могу понять почему так сделано и это абсолютно имеет право на жизнь, но блин стейт слишком маленький))
В нем всего два поля и выносить его в отдельный файл как-то ну совсем ту мач. Обычно сам начальный стейт указываем в файле с редьюсером, а вот интерфейс для этого начального стейта действительно можно и стоит вынести отдельно.
Выносить сам начальный стейт в отдельный файл (а интерфейс для него в еще один отдельный файл) наверно круто, если он огромный типо 20+ полей или там большая вложенность и т.д.

https://github.com/daniilkiselev97/meetups-project/blob/31391bf24298b157dae8945e860608636dfb07c5/src/app/store/state/auth.state.ts#L1-L13

**Comment by daniilkiselev97** [comment]
https://github.com/daniilkiselev97/meetups-project/commit/0179457dfb4c559362860bf37c36a421d2bd8f31
