### ISSUE TITLE
Перешли на Призму, но остались на Тайге

### ISSUE THREAD

**Issue by Anna-Prokhorova** [daniilkiselev97/meetups-project#9]
Как-то странно, что контрол призмовский, а конструктор значения этого контрола таежный...
У меня есть офигенное предложение удалить зависимости тайги из package.json и реально перейти на призму)

https://github.com/daniilkiselev97/meetups-project/blob/31391bf24298b157dae8945e860608636dfb07c5/src/app/components/popup-create-meetup/popup-create-meetup.component.ts#L86-L87

**Comment by daniilkiselev97** [comment]
https://github.com/daniilkiselev97/meetups-project/commit/3745ebbcbe9f9cd1a451bfcd05fdc117a89c13ad#diff-89bc35116672b782320481f4de92cad51dc5e7a19cdb92ccee38b27763318a1e

**Comment by daniilkiselev97** [comment]
https://github.com/daniilkiselev97/meetups-project/commit/3745ebbcbe9f9cd1a451bfcd05fdc117a89c13ad
